name: da4ds
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.4.2
  - astroid=2.3.3
  - blas=1.0
  - bokeh=2.0.1
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - click=7.1.2
  - cloudpickle=1.4.1
  - colorama=0.4.3
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.10.1
  - dask-core=2.10.1
  - distributed=2.15.2
  - flask=1.1.1
  - flask-migrate=2.4.0
  - flask-socketio=3.3.2
  - flask-sqlalchemy=2.4.0
  - freetype=2.10.1
  - fsspec=0.7.3
  - heapdict=1.0.1
  - icc_rt=2019.0.0
  - icu=64.2
  - intel-openmp=2019.4
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9c
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - mako=1.1.0
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - msgpack-python=1.0.0
  - numpy=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.1
  - partd=1.1.0
  - pillow=7.1.2
  - pip=20.1
  - psutil=5.7.0
  - pylint=2.4.4
  - pyodbc=4.0.28
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-dotenv=0.10.5
  - python-editor=1.0.4
  - python-engineio=3.11.2
  - python-socketio=3.1.2
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.12.5
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sortedcontainers=2.1.0
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - tblib=1.6.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wincertstore=0.2
  - wrapt=1.12.1
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.4
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - backcall==0.1.0
    - decorator==4.4.1
    - intervaltree==3.0.2
    - ipython==7.12.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - lxml==4.5.0
    - networkx==2.4
    - ortools==7.4.7247
    - parso==0.6.1
    - pickleshare==0.7.5
    - graphviz==0.16
    - pm4py==2.2.7.1
    - prompt-toolkit==3.0.3
    - protobuf==3.11.3
    - pulp==2.0
    - pyarrow==0.15.1
    - pydotplus==2.0.2
    - pygments==2.5.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - python-graphviz==0.13.2
    - pyvis==0.1.7.0
    - traitlets==4.3.3
    - wcwidth==0.1.8