"""add event log location

Revision ID: 004890c1aa17
Revises: 421df62f1bdb
Create Date: 2020-06-05 11:24:33.780196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004890c1aa17'
down_revision = '421df62f1bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_information', sa.Column('EventLogLocation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_information', 'EventLogLocation')
    # ### end Alembic commands ###
