"""Add Xes Attributes

Revision ID: 22a97f6c35c7
Revises: 81df97e09b0d
Create Date: 2020-05-12 13:17:01.000604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a97f6c35c7'
down_revision = '81df97e09b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_information', sa.Column('PMXesAttributes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_information', 'PMXesAttributes')
    # ### end Alembic commands ###
