"""initial_migration

Revision ID: 2aa039f329c9
Revises: 
Create Date: 2019-10-17 16:27:36.289698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa039f329c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('ServiceScope', sa.String(length=255), nullable=True),
    sa.Column('Resource', sa.String(length=444), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('dataBaseDialect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialectParameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frontend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('Resource', sa.String(length=444), nullable=True),
    sa.Column('Method', sa.String(length=255), nullable=True),
    sa.Column('Counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('inflexible_data_source_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_server', sa.String(length=128), nullable=True),
    sa.Column('db_name', sa.String(length=128), nullable=True),
    sa.Column('trusted_connection', sa.Boolean(), nullable=True),
    sa.Column('query', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reshaped_backend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('ServiceScope', sa.String(length=255), nullable=True),
    sa.Column('Call', sa.String(length=444), nullable=True),
    sa.Column('Rid', sa.String(length=444), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('reshaped_frontend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('Page', sa.String(length=800), nullable=True),
    sa.Column('Method', sa.String(length=800), nullable=True),
    sa.Column('Rid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('association',
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dataBaseDialect.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['dialectParameters.id'], )
    )
    op.create_table('data_source_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('parameter_values', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dataBaseDialect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source_connection')
    op.drop_table('association')
    op.drop_table('reshaped_frontend_logs')
    op.drop_table('reshaped_backend_logs')
    op.drop_table('inflexible_data_source_connection')
    op.drop_table('frontend_logs')
    op.drop_table('dialectParameters')
    op.drop_table('dataBaseDialect')
    op.drop_table('backend_logs')
    # ### end Alembic commands ###
