"""add data table

Revision ID: 3ea859a2b2f7
Revises: 2aa039f329c9
Create Date: 2020-03-06 11:28:22.653379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea859a2b2f7'
down_revision = '2aa039f329c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Type', sa.String(length=255), nullable=True),
    sa.Column('StoredOnServer', sa.Boolean(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.Column('Parameters', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source')
    # ### end Alembic commands ###
