"""added column for source data location

Revision ID: 421df62f1bdb
Revises: d9316ebe4191
Create Date: 2020-06-02 13:53:52.975147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421df62f1bdb'
down_revision = 'd9316ebe4191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_information', sa.Column('UnmodifiedDataLocation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_information', 'UnmodifiedDataLocation')
    # ### end Alembic commands ###
