"""create rudimentary session table


Revision ID: 81df97e09b0d
Revises: 3ea859a2b2f7
Create Date: 2020-03-17 23:29:58.612898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81df97e09b0d'
down_revision = '3ea859a2b2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_information',
    sa.Column('Id', sa.String(length=64), nullable=False),
    sa.Column('WorkingDataLocation', sa.String(length=255), nullable=True),
    sa.Column('OutputDataLocation', sa.String(length=255), nullable=True),
    sa.Column('PMFilters', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_information')
    # ### end Alembic commands ###
