"""add pm options

Revision ID: 84160b285ffb
Revises: 004890c1aa17
Create Date: 2020-06-05 12:36:26.195785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84160b285ffb'
down_revision = '004890c1aa17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_information', sa.Column('PMOptions', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_information', 'PMOptions')
    # ### end Alembic commands ###
