"""empty message

Revision ID: e8bee1a30569
Revises: 
Create Date: 2021-05-26 16:38:53.466884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bee1a30569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('ServiceScope', sa.String(length=255), nullable=True),
    sa.Column('Resource', sa.String(length=444), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('dataBaseDialect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Type', sa.String(length=255), nullable=True),
    sa.Column('StoredOnServer', sa.Boolean(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.Column('Parameters', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('dialectParameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frontend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('Resource', sa.String(length=444), nullable=True),
    sa.Column('Method', sa.String(length=255), nullable=True),
    sa.Column('Counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('inflexible_data_source_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_server', sa.String(length=128), nullable=True),
    sa.Column('db_name', sa.String(length=128), nullable=True),
    sa.Column('trusted_connection', sa.Boolean(), nullable=True),
    sa.Column('query', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reshaped_backend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('ServiceScope', sa.String(length=255), nullable=True),
    sa.Column('Call', sa.String(length=444), nullable=True),
    sa.Column('Rid', sa.String(length=444), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('reshaped_frontend_logs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=True),
    sa.Column('AccessToken', sa.String(length=255), nullable=True),
    sa.Column('Page', sa.String(length=800), nullable=True),
    sa.Column('Method', sa.String(length=800), nullable=True),
    sa.Column('Rid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('session_information',
    sa.Column('Id', sa.String(length=64), nullable=False),
    sa.Column('UnmodifiedDataLocation', sa.String(length=255), nullable=True),
    sa.Column('WorkingDataLocation', sa.String(length=255), nullable=True),
    sa.Column('PDDataLocation', sa.String(length=255), nullable=True),
    sa.Column('EventLogLocation', sa.String(length=255), nullable=True),
    sa.Column('OutputDataLocation', sa.String(length=255), nullable=True),
    sa.Column('PMXesAttributes', sa.String(length=2000), nullable=True),
    sa.Column('PMFilters', sa.String(length=2000), nullable=True),
    sa.Column('PMOptions', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('association',
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dataBaseDialect.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['dialectParameters.id'], )
    )
    op.create_table('data_source_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('parameter_values', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dataBaseDialect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source_connection')
    op.drop_table('association')
    op.drop_table('session_information')
    op.drop_table('reshaped_frontend_logs')
    op.drop_table('reshaped_backend_logs')
    op.drop_table('inflexible_data_source_connection')
    op.drop_table('frontend_logs')
    op.drop_table('dialectParameters')
    op.drop_table('data_source')
    op.drop_table('dataBaseDialect')
    op.drop_table('backend_logs')
    # ### end Alembic commands ###
